global_plotting_options:
 regions: ["cerra"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  metrics  : ["rmse"]
  regions: ["cerra"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/MF/eval_plots/CERRA_experiments/latent_space"
  plot_ensemble: false #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  CERRA:
    channels: ['10si', 'r_850'] #, "blah"] #["2t", "msl", "r_850", "t_850", "u_850", "v_850", "z_850"] #
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"
    plotting:
      sample: [1,2,3]
      forecast_step: "all"
      ensemble: "mean"
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :

      # kcxgtv5v:
      #     label: "I: ERA - O:CERRA "
      #     color: "tab:blue"
      #     rank: "all"
      # dt365rog:
      #     label: "I: ERA - O:CERRA - ft from 2016-01-01"
      #     color: "tab:green"
      #     rank: "all"
      # sref67hi:
      #     label: "I: ERA - O:CERRA - dim_embed: 1024"
      #     color: "tab:orange"
      #     rank: "all"
      # kqv7rvey:
      #     label: "I: ERA+CERRA - O:CERRA "
      #     color: "tab:red"
      #     rank: "all"
      
      wn4r44o7:
          label: "dim_embed: 1024 - num_layers : 4 - num_heads : 8"
          color: "tab:blue"
          rank: "all"
      
      qnbltz0n:
          label: "dim_embed: 1024 - num_layers : 2 - num_heads : 4"
          color: "tab:green"
          rank: "all"
