
global_plotting_options:
 regions: ["cerra"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  metrics  : ["rmse"]
  regions: ["cerra"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/MF_KNMI/eval_plots/CERRA_experiments/structure_loss"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  CERRA:
    channels: ['2t', 'msl', tp, '10si', '10wdir', 'r_850', 't_850', 'u_850', 'v_850', 'z_850'] #, "blah"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "mean"
    plotting:
      sample: [0,1,2,3]
      forecast_step: "all"
      ensemble: "mean"
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :

  lca7rnty:
    #type: "json"
    label: "Wael-Pretraining"
    rank: "all"
    color: "tab:blue"
  nle7pvpz:
    #type: "json"
    label: "Wael-ST Finetuning"
    rank: "all"
    color: "darkblue"

  oikse6ab:
    #type: "json"
    label: "Pretraining-coords-config"
    rank: "all"
    color: "tab:red"
  tki7yn5w:
    #type: "json"
    label: "ST Finetuning-coords-config"
    rank: "all"
    color: "darkred"
  
  sqkzr7h5:
    #type: "json"
    label: "Pretraining-coords-hack"
    rank: "all"
    color: "tab:green"
  qed9sgn0:
    #type: "json"
    label: "ST Finetuning-coords-hack"
    rank: "all"
    color: "darkgreen"

