
global_plotting_options:
 regions: ["global"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  metrics  : ["rmse","bias","mae"]
  regions: ["global"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/MF_KNMI/eval_plots/CERRA_experiments/structure_loss"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  ERA5:
    channels: ['q_850'] #, "blah"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "mean"
    plotting:
      sample: [0,15]
      forecast_step: "all"
      ensemble: "mean"
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :

  oikse6ab:
    label: "CERRA-baseline"
    rank: "all"

  # lca7rnty :
  #   #type: "json"
  #   label: "CERRA-baseline-Wael"
  #   rank: "all"
  #   # color: "tab:yellow"

  # nle7pvpz :
  #   #type: "json"
  #   label: "CERRA-str-loss-ft-Wael"
  #   rank: "all"
  #   # color: "tab:yellow"

