
global_plotting_options:
 regions: ["cerra"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  metrics  : ["rmse"]
  regions: ["cerra"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/MF_KNMI/eval_plots/CERRA_experiments/abs_coords"
  plot_ensemble: false #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  CERRA:
    channels: ["2t", "msl", "r_850", "t_850", "u_850", "v_850", "z_850"] #, "blah"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"
    plotting:
      sample: [1,2,3]
      forecast_step: "all"
      ensemble: "mean"
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :


      d66ybgzi:
        label: "CERRA rel coord 3h-3h - ema 1e-3"
        color: "tab:red"
        rank: "all"

      n5620w0v:
          label: "CERRA abs hack 3h-3h - ema 1e-3"
          color: "tab:blue"
          rank: "all"
      
      sqoiwyqo:
          label: "CERRA abs hack 3h-3h - ema 600"
          color: "tab:blue"
          rank: "all"

      zozst8cy:
          label: "CERRA abs config 3h-3h - ema 1e-3"
          color: "tab:green"
          rank: "all"

      euzaa9w5:
          label: "CERRA abs hack 3h-3h - unembed block - ema 1e-3"
          color: "tab:purple"
          rank: "all"

      j9e9d371:
          label: "CERRA abs hack 3h-3h - ext fields - ema 1e-3"
          color: "tab:pink"
          rank: "all"

      p4zy2yt4:
          label: "CERRA abs hack 3h-3h - ema 1e-3 - C.L. decoder"
          color: "tab:brown"
          rank: "all"


      





  # # anjop5jc:
  # #   #type: "json"
  # #   label: "CERRA coord hack 3h-6h - 1fstep - E128"
  # #   rank: "all"
  # #   color: "tab:blue"
  
  # h4gmfgxk:
  #   #type: "json"
  #   label: "CERRA coord hack 3h-6h - 1fstep - E210"
  #   rank: "all"
  #   color: "darkblue"

  # wr6313s0:
  #   #type: "json"
  #   label: "CERRA coord hack 3h-6h - 1fstep - E256"
  #   rank: "all"
  #   color: "tab:blue"

  # iwwxh4gj:
  #   #type: "json"
  #   label: "CERRA coord hack 6h-6h - 1fstep - E210"
  #   rank: "all"
  #   color: "red"

  # o9znnxt6:
  #   #type: "json"
  #   label: "CERRA coord hack 6h-6h - 1fstep - E256"
  #   rank: "all"
  #   color: "tab:red"

  # # ssc50lcg:
  # #   #type: "json"
  # #   label: "CERRA coord hack 3h-3h - 1fstep - 128"
  # #   rank: "all"
  # #   color: "tab:orange"

  # p7m760wc:
  #   #type: "json"
  #   label: "CERRA coord hack 3h-3h - 1fstep - E210"
  #   rank: "all"
  #   color: "orange"

  # sqoiwyqo:
  #   #type: "json"
  #   label: "CERRA coord hack 3h-3h - 1fstep - E256"
  #   rank: "all"
  #   color: "tab:orange"

  # # s9a4ybry:
  # #   #type: "json"
  # #   label: "CERRA coord config 3h-3h - 1fstep - E128"
  # #   rank: "all"
  # #   color: "tab:green"

  # # b0hsmun4:
  # #   #type: "json"
  # #   label: "CERRA coord hack 6h-6h - 1fstep - E128"
  # #   rank: "all"
  # #   color: "tab:red"

  # # gvd3azra:
  # #   #type: "json"
  # #   label: "CERRA coord hack 3h-3h - 1fstep - E128 - mnt: -1"
  # #   rank: "all"
  # #   color: "tab:purple"

  # # zt8dihgw:
  # #   label: "CERRA coord hack 3h-3h - 3fstep - 128"
  # #   rank: "all"
  # #   color: "tab:brown"

  # # s26tbvk8:
  # #   label: "CERRA + surf wind coord hack 3h-3h - 3fstep - 128"
  # #   rank: "all"
  # #   color: "tab:pink"


  # ybvdf773:
  #   #type: "json"
  #   label: "CERRA coord config 3h-3h - 1fstep - E210"
  #   rank: "all"
  #   color: "green"

  # zozst8cy:
  #   #type: "json"
  #   label: "CERRA coord config 3h-3h - 1fstep - E256"
  #   rank: "all"
  #   color: "tab:green"

  # yyfol4hc:
  #   #type: "json"
  #   label: "CERRA coord hack 3h-3h - 3fstep - E210"
  #   rank: "all"
  #   color: "tab:brown"

  # x9py94n6:
  #   #type: "json"
  #   label: "CERRA + surf wind coord hack 3h-3h - 3fstep - E210"
  #   rank: "all"
  #   color: "tab:pink"