train:
  plot:
    srdq64fs : 
        slurm_id : 0
        description: "Wael-Pretraining"
        color: "tab:blue"
    jcw6d6fh: 
        slurm_id : 0
        description : "Wael-ST Finetuning"
        color: "darkblue"
    
    la5nfskr : 
        slurm_id : 0
        description: "Pretraining-coords-config"
        color: "tab:red"
    hgjeze93: 
        slurm_id : 0
        description : "ST Finetuning-coords-config"
        color: "darkred"

    gh7wv8ce : 
        slurm_id : 0
        description: "Pretraining-coords-hack"
        color: "tab:green"
    dkmt08yz : 
        slurm_id : 0
        description : "ST Finetuning-coords-hack"
        color: "darkgreen"