stages:
  - name: pretrain
    stage: train
    config_files:
      - config/config_forecasting_era5_cerra.yml
    options:
      - training_config.num_mini_epochs=32
    chain_jobs: 4
    nodes: 2
    slurm_args:
      - "--time=23:59:00"
      


