stages:
  - name: inf
    stage: inference
    from_run_id : f0gsfpui
    config_files:
      - config/config_forecasting_era5_cerra_inf.yml
    chain_jobs: 1
    nodes: 1
    slurm_args:
      - "--time=23:59:00" 


