stages:
  - name: pretrain
    stage: train
    config_files:
      - config/config_forecasting_era5_cerra_cont.yml
    from_run_id: pagdni21
    mini_epoch: 29
    options:
      - training_config.num_mini_epochs=64
      - data_loading.num_workers=8
    chain_jobs: 4
    nodes: 2
    slurm_args:
      - "--time=23:59:00"
      


